
create table agente (
    id bigint primary key generated by default as identity,
    chave varchar( 100 ) not null,
    nome varchar( 255 ) not null,
    empresa_id bigint not null,
    constraint empresa_fk foreign key( empresa_id ) references empresa( id )
);