drop table if exists usuario_grupo_map;
drop table if exists role_grupo_map;
drop table if exists usuario;
drop table if exists usuario_grupo;
drop table if exists role;

drop table if exists dispositivo;
drop table if exists empresa;

drop table if exists config;

create table config (
    id int primary key generated by default as identity,
    max_falhas_consecutivas int default 5,
    num_pacotes_por_vez int default 15,
    monitoramento_delay int default 20000
);

create table empresa (
    id int primary key generated by default as identity,
    nome varchar( 255 ) not null unique,
    email_notif varchar( 100 )
);

create table dispositivo (
    id int primary key generated by default as identity,
    nome varchar( 255 ) not null unique,
    descricao varchar( 511 ),
    localizacao varchar( 255 ) not null,
    sendo_monitorado boolean default false,
    empresa_id int not null,
    constraint empresa_fk foreign key( empresa_id ) references empresa( id )
);

create table usuario (
    id int primary key generated by default as identity,
    nome varchar( 256 ) not null,
    email varchar( 100 ) not null,
    username varchar( 100 ) not null unique,
    senha varchar( 128 ) not null,
    empresa_id int,
    constraint empresa_fk foreign key( empresa_id ) references empresa( id )
);

create table usuario_grupo (
    id int primary key generated by default as identity,
    nome varchar( 256 ) not null unique
);

create table role (
    id int primary key generated by default as identity,
    nome varchar( 256 ) not null unique
);

create table usuario_grupo_map (
    id int primary key generated by default as identity,
    usuario_id int,
    usuario_grupo_id int,
    constraint usuario_fk foreign key( usuario_id ) references usuario( id ),
    constraint usuario_grupo_fk foreign key( usuario_grupo_id ) references usuario_grupo( id )
);

create table role_grupo_map (
    id int primary key generated by default as identity,
    role_id int,
    role_grupo_id int,
    constraint role_fk foreign key( role_id ) references role( id ),
    constraint role_grupo_fk foreign key( role_grupo_id ) references usuario_grupo( id )
);

delete from usuario_grupo_map;
delete from role_grupo_map;
delete from usuario;
delete from usuario_grupo;
delete from role;

insert into usuario( nome, email, username, senha ) values (
    'Italo Herbert',
    'italoherbert@outlook.com',
    'italo',
    '59f62a0320ea304cbec2498764c5c6742bfcabf1b591e26a3bea6bfcca3e358e'
);

insert into usuario_grupo ( nome ) values ( 'admin' );
insert into usuario_grupo ( nome ) values ( 'suporte' );

insert into role ( nome ) values
    ( 'usuario-write' ),
    ( 'usuario-read' ),
    ( 'usuario-get' ),
    ( 'usuario-delete' ),
    ( 'usuario-grupo-write' ),
    ( 'usuario-grupo-read' ),
    ( 'usuario-grupo-delete' ),
    ( 'role-write' ),
    ( 'role-read' ),
    ( 'role-delete' ),
    ( 'empresa-read' ),
    ( 'empresa-write' ),
    ( 'empresa-delete' ),
    ( 'empresa-get' ),
    ( 'dispositivo-read' ),
    ( 'dispositivo-write' ),
    ( 'dispositivo-delete' );

insert into usuario_grupo_map( usuario_id, usuario_grupo_id ) values
    ( (select id from usuario where username='italo'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from usuario where username='italo'), (select id from usuario_grupo where nome='suporte') );

insert into role_grupo_map( role_id, usuario_grupo_id ) values
    ( (select id from role where nome='usuario-write'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='usuario-read'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='usuario-delete'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='usuario-grupo-write'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='usuario-grupo-read'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='usuario-grupo-delete'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='role-write'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='role-read'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='role-delete'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='empresa-read'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='empresa-write'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='empresa-delete'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='dispositivo-write'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='dispositivo-read'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='dispositivo-delete'), (select id from usuario_grupo where nome='admin') ),

    ( (select id from role where nome='usuario-get'), (select id from usuario_grupo where nome='suporte') ),
    ( (select id from role where nome='empresa-get'), (select id from usuario_grupo where nome='suporte') ),
    ( (select id from role where nome='dispositivo-write'), (select id from usuario_grupo where nome='suporte') ),
    ( (select id from role where nome='dispositivo-read'), (select id from usuario_grupo where nome='suporte') ),
    ( (select id from role where nome='dispositivo-delete'), (select id from usuario_grupo where nome='suporte') );