drop table if exists usuario_grupo_map;
drop table if exists role_grupo_map;
drop table if exists usuario;
drop table if exists usuario_grupo;
drop table if exists role;

drop table if exists evento;

drop table if exists dispositivo;
drop table if exists agente;
drop table if exists empresa;

drop table if exists config;
drop table if exists monitor_server;

create table config (
    id bigint primary key generated by default as identity,
    num_pacotes_por_lote int default 15,
    monitoramento_delay int default 1,
    registro_evento_periodo int default 3600,
    num_threads_limite int default 32,
    monitor_server_corrente int default 0,
    telegram_bot_token varchar( 100 ) default '',
    valor_pagto double precision default 250
);

create table monitor_server (
    id bigint primary key generated by default as identity,
    host varchar( 255 ) not null
);

create table empresa (
    id bigint primary key generated by default as identity,
    nome varchar( 255 ) not null unique,
    email_notif varchar( 100 ),
    telegram_chat_id varchar( 50 ) default '',
    max_dispositivos_quant int default 50,
    porcentagem_max_falhas_por_lote double precision default 0.3333,
    min_tempo_para_prox_notif int default 3600,
    dia_pagto int default 1,
    temporario boolean default false,
    uso_temporario_por int default 7,
    bloqueada boolean default false,
    ultima_notif_em timestamp default current_timestamp,
    criado_em timestamp default current_timestamp,
    uso_regular_iniciado_em date,
    pago_ate date
);

create table agente (
    id bigint primary key generated by default as identity,
    chave varchar( 100 ) not null,
    nome varchar( 255 ) not null,
    ultimo_envio_de_estado_em timestamp default current_timestamp,
    empresa_id bigint not null,
    constraint empresa_fk foreign key( empresa_id ) references empresa( id )
);

create table dispositivo (
    id bigint primary key generated by default as identity,
    nome varchar( 255 ) not null,
    host varchar( 100 ) not null,
    descricao varchar( 511 ),
    localizacao varchar( 255 ) not null,
    sendo_monitorado boolean default false,
    status varchar(20) not null,
    latencia_media int default 0,
    state_atualizado_em timestamp default current_timestamp,
    monitorado_por_agente boolean default false,
    empresa_id bigint not null,
    agente_id bigint,
    constraint empresa_fk foreign key( empresa_id ) references empresa( id ),
    constraint agente_fk foreign key( agente_id ) references agente( id )
);

create table evento (
    id bigint primary key generated by default as identity,
    sucessos_quant int not null,
    falhas_quant int not null,
    quedas_quant int not null,
    tempo_inatividade int not null,
    duracao int not null,
    criado_em timestamp default current_timestamp,
    dispositivo_id bigint not null,
    constraint dispositivo_fk foreign key( dispositivo_id ) references dispositivo( id )
);

create table usuario (
    id bigint primary key generated by default as identity,
    nome varchar( 256 ) not null,
    email varchar( 100 ) not null,
    username varchar( 100 ) not null unique,
    senha varchar( 128 ) not null,
    perfil varchar( 20 ) not null,
    empresa_id bigint,
    constraint empresa_fk foreign key( empresa_id ) references empresa( id )
);

create table usuario_grupo (
    id bigint primary key generated by default as identity,
    nome varchar( 256 ) not null unique
);

create table role (
    id bigint primary key generated by default as identity,
    nome varchar( 256 ) not null unique
);

create table usuario_grupo_map (
    id bigint primary key generated by default as identity,
    usuario_id bigint not null,
    usuario_grupo_id bigint not null,
    constraint usuario_fk foreign key( usuario_id ) references usuario( id ),
    constraint usuario_grupo_fk foreign key( usuario_grupo_id ) references usuario_grupo( id )
);

create table role_grupo_map (
    id bigint primary key generated by default as identity,
    role_id bigint not null,
    usuario_grupo_id bigint not null,
    constraint role_fk foreign key( role_id ) references role( id ),
    constraint usuario_grupo_fk foreign key( usuario_grupo_id ) references usuario_grupo( id )
);

insert into config ( num_pacotes_por_lote, monitoramento_delay, registro_evento_periodo, monitor_server_corrente ) values (
    15, 1, 3600, 0
);

insert into usuario( nome, email, username, senha, perfil ) values (
    'Italo Herbert',
    'italoherbert@outlook.com',
    'italo',
    '59f62a0320ea304cbec2498764c5c6742bfcabf1b591e26a3bea6bfcca3e358e',
    'ADMIN'
);

insert into usuario_grupo ( nome ) values ( 'admin' );
insert into usuario_grupo ( nome ) values ( 'suporte' );

insert into role ( nome ) values
    ( 'usuario-all' ),
    ( 'usuario-grupo-all' ),
    ( 'role-all' ),
    ( 'empresa-all' ),
    ( 'dispositivo-all' ),
    ( 'dispositivo-monitoramento-all'),
    ( 'config-all' ),
    ( 'pagamentos-all' ),
    ( 'agente-all' ),

    ( 'usuario-get' ),
    ( 'empresa-get' ),
    ( 'dispositivo-get' ),
    ( 'usuario-alter-senha' ),
    ( 'start-or-stop-all-monitoramentos' ),
    ( 'no-admin-update-empresa'),
    ( 'no-admin-config-get' ),
    ( 'pix-qrcode-get' ),
    ( 'pagamentos-get');

insert into usuario_grupo_map( usuario_id, usuario_grupo_id ) values
    ( (select id from usuario where username='italo'), (select id from usuario_grupo where nome='admin') );

insert into role_grupo_map( role_id, usuario_grupo_id ) values
    ( (select id from role where nome='usuario-all'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='usuario-grupo-all'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='role-all'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='empresa-all'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='dispositivo-all'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='dispositivo-monitoramento-all'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='config-all'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='pagamentos-all'), (select id from usuario_grupo where nome='admin') ),    
    ( (select id from role where nome='agente-all'), (select id from usuario_grupo where nome='admin') ),    
    ( (select id from role where nome='start-or-stop-all-monitoramentos'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='usuario-alter-senha'), (select id from usuario_grupo where nome='admin') ),    

    ( (select id from role where nome='usuario-get'), (select id from usuario_grupo where nome='suporte') ),
    ( (select id from role where nome='empresa-get'), (select id from usuario_grupo where nome='suporte') ),
    ( (select id from role where nome='dispositivo-all'), (select id from usuario_grupo where nome='suporte') ),
    ( (select id from role where nome='dispositivo-monitoramento-all'), (select id from usuario_grupo where nome='suporte') ),
    ( (select id from role where nome='agente-all'), (select id from usuario_grupo where nome='suporte') ),
    ( (select id from role where nome='no-admin-update-empresa'), (select id from usuario_grupo where nome='suporte') ),
    ( (select id from role where nome='usuario-alter-senha'), (select id from usuario_grupo where nome='suporte') ),
    ( (select id from role where nome='no-admin-config-get'), (select id from usuario_grupo where nome='suporte') ),
    ( (select id from role where nome='pagamentos-get'), (select id from usuario_grupo where nome='suporte') ),
    ( (select id from role where nome='pix-qrcode-get'), (select id from usuario_grupo where nome='suporte') );
