drop table if exists usuario_grupo_map;
drop table if exists role_grupo_map;
drop table if exists usuario;
drop table if exists usuario_grupo;
drop table if exists role;

drop table if exists evento;

drop table if exists dispositivo;
drop table if exists empresa;

drop table if exists config;

create table config (
    id bigint primary key generated by default as identity,
    num_pacotes_por_lote int default 15,
    monitoramento_delay int default 1,
    registro_evento_periodo int default 3600
);

create table empresa (
    id bigint primary key generated by default as identity,
    nome varchar( 255 ) not null unique,
    email_notif varchar( 100 ),
    porcentagem_max_falhas_por_lote double precision default 0.3333
);

create table dispositivo (
    id bigint primary key generated by default as identity,
    nome varchar( 255 ) not null unique,
    descricao varchar( 511 ),
    localizacao varchar( 255 ) not null,
    sendo_monitorado boolean default false,
    status varchar(255) check (status in ('ATIVO','INATIVO')) default 'INATIVO',
    empresa_id bigint not null,
    constraint empresa_fk foreign key( empresa_id ) references empresa( id )
);

create table evento (
    id bigint primary key generated by default as identity,
    sucessos_quant int not null,
    falhas_quant int not null,
    quedas_quant int not null,
    tempo_inatividade int not null,
    criado_em timestamp default current_timestamp,
    dispositivo_id bigint not null,
    constraint dispositivo_fk foreign key( dispositivo_id ) references dispositivo( id )
);

create table usuario (
    id bigint primary key generated by default as identity,
    nome varchar( 256 ) not null,
    email varchar( 100 ) not null,
    username varchar( 100 ) not null unique,
    senha varchar( 128 ) not null,
    empresa_id bigint,
    constraint empresa_fk foreign key( empresa_id ) references empresa( id )
);

create table usuario_grupo (
    id int primary key generated by default as identity,
    nome varchar( 256 ) not null unique
);

create table role (
    id int primary key generated by default as identity,
    nome varchar( 256 ) not null unique
);

create table usuario_grupo_map (
    id bigint primary key generated by default as identity,
    usuario_id bigint not null,
    usuario_grupo_id bigint not null,
    constraint usuario_fk foreign key( usuario_id ) references usuario( id ),
    constraint usuario_grupo_fk foreign key( usuario_grupo_id ) references usuario_grupo( id )
);

create table role_grupo_map (
    id int primary key generated by default as identity,
    role_id bigint not null,
    usuario_grupo_id bigint not null,
    constraint role_fk foreign key( role_id ) references role( id ),
    constraint usuario_grupo_fk foreign key( usuario_grupo_id ) references usuario_grupo( id )
);

insert into config ( num_pacotes_por_lote, monitoramento_delay, registro_evento_periodo ) values (
    15, 1, 3600
);

insert into usuario( nome, email, username, senha ) values (
    'Italo Herbert',
    'italoherbert@outlook.com',
    'italo',
    '59f62a0320ea304cbec2498764c5c6742bfcabf1b591e26a3bea6bfcca3e358e'
);

insert into usuario_grupo ( nome ) values ( 'admin' );
insert into usuario_grupo ( nome ) values ( 'suporte' );

insert into role ( nome ) values
    ( 'usuario-write' ),
    ( 'usuario-read' ),
    ( 'usuario-get' ),
    ( 'usuario-delete' ),
    ( 'usuario-grupo-write' ),
    ( 'usuario-grupo-read' ),
    ( 'usuario-grupo-delete' ),
    ( 'role-write' ),
    ( 'role-read' ),
    ( 'role-delete' ),
    ( 'empresa-read' ),
    ( 'empresa-write' ),
    ( 'empresa-delete' ),
    ( 'empresa-get' ),
    ( 'dispositivo-read' ),
    ( 'dispositivo-write' ),
    ( 'dispositivo-delete' ),
    ( 'dispositivo-monitoramento'),
    ( 'config-write' ),
    ( 'config-read' );

insert into usuario_grupo_map( usuario_id, usuario_grupo_id ) values
    ( (select id from usuario where username='italo'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from usuario where username='italo'), (select id from usuario_grupo where nome='suporte') );

insert into role_grupo_map( role_id, usuario_grupo_id ) values
    ( (select id from role where nome='usuario-write'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='usuario-read'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='usuario-delete'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='usuario-grupo-write'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='usuario-grupo-read'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='usuario-grupo-delete'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='role-write'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='role-read'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='role-delete'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='empresa-read'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='empresa-write'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='empresa-delete'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='dispositivo-write'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='dispositivo-read'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='dispositivo-delete'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='dispositivo-monitoramento'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='config-write'), (select id from usuario_grupo where nome='admin') ),
    ( (select id from role where nome='config-read'), (select id from usuario_grupo where nome='admin') ),

    ( (select id from role where nome='usuario-get'), (select id from usuario_grupo where nome='suporte') ),
    ( (select id from role where nome='empresa-get'), (select id from usuario_grupo where nome='suporte') ),
    ( (select id from role where nome='dispositivo-write'), (select id from usuario_grupo where nome='suporte') ),
    ( (select id from role where nome='dispositivo-read'), (select id from usuario_grupo where nome='suporte') ),
    ( (select id from role where nome='dispositivo-delete'), (select id from usuario_grupo where nome='suporte') ),
    ( (select id from role where nome='dispositivo-monitoramento'), (select id from usuario_grupo where nome='suporte') );
