
create table empresa (
    id int primary key generated by default as identity,
    nome varchar( 256 ) not null unique,
    email_notif varchar( 100 )
);

alter table usuario add column empresa_id int;
alter table usuario add constraint empresa_fk foreign key( empresa_id ) references empresa( id );

insert into role ( nome ) values
    ('empresa-read'),
    ('empresa-write'),
    ('empresa-delete'),
    ('empresa-get');

insert into role_grupo_map ( role_id, usuario_grupo_id ) values
    ((select id from role where nome='empresa-read'), (select id from usuario_grupo where nome='admin') ),
    ((select id from role where nome='empresa-write'), (select id from usuario_grupo where nome='admin') ),
    ((select id from role where nome='empresa-delete'), (select id from usuario_grupo where nome='admin') ),
    ((select id from role where nome='empresa-get'), (select id from usuario_grupo where nome='suporte') );