
alter table empresa add column max_falhas_consecutivas int;
alter table empresa add column monitoramento_delay int;
alter table empresa add column num_pacotes_por_vez int;

update empresa set max_falhas_consecutivas=5, monitoramento_delay=20000, num_pacotes_por_vez=15;

alter table empresa alter column max_falhas_consecutivas set not null;
alter table empresa alter column monitoramento_delay set not null;
alter table empresa alter column num_pacotes_por_vez set not null;

drop table if exists dispositivo;

create table dispositivo (
    id int primary key generated by default as identity,
    nome varchar( 255 ) not null unique,
    descricao varchar( 511 ),
    localizacao varchar( 255 ) not null,
    sendo_monitorado boolean,
    empresa_id int not null,
    constraint empresa_fk foreign key( empresa_id ) references empresa( id )
);