alter table empresa drop column max_falhas_consecutivas;
alter table empresa drop column monitoramento_delay;
alter table empresa drop column num_pacotes_por_vez;

drop table if exists config;

create table config (
    id int primary key generated by default as identity,
    max_falhas_consecutivas int default 5,
    num_pacotes_por_vez int default 15,
    monitoramento_delay int default 20000
);