
create table evento (
    id int primary key generated by default as identity,
    sucessosQuant int not null,
    falhasQuant int not null,
    quedasQuant int not null,
    tempoInatividade int not null,
    criadoEm timestamp default current_timestamp,
    dispositivo_id int not null,
    constraint dispositivo_fk foreign key( dispositivo_id ) references dispositivo( id )
);