drop table if exists evento;

create table evento (
    id bigint primary key generated by default as identity,
    sucessos_quant int not null,
    falhas_quant int not null,
    quedas_quant int not null,
    tempo_inatividade int not null,
    criado_em timestamp default current_timestamp,
    dispositivo_id bigint not null,
    constraint dispositivo_fk foreign key( dispositivo_id ) references dispositivo( id )
);